# Generated by Django 5.0.6 on 2026-04-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_ai_provider',
            field=models.CharField(choices=[('openai', 'OpenAI GPT'), ('gemini', 'Google Gemini')], default='openai', help_text='偏好的 AI 分析模型', max_length=20),
        ),
    ]
