# Generated by Django 5.0.6 on 2026-04-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_preferred_ai_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_ai_provider',
            field=models.CharField(choices=[('openai', 'OpenAI GPT'), ('gemini', 'Google Gemini')], default='openai', help_text='偏好的AI模型提供者', max_length=20),
        ),
    ]
