# Generated by Django 5.0.6 on 2026-04-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_preferred_ai_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='daily_calorie_target',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', '男性'), ('female', '女性'), ('other', '其他')], help_text='請選擇性別', max_length=10, null=True, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, help_text='出生日期', null=True, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='建立時間', verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='user',
            name='goal',
            field=models.CharField(choices=[('lose_weight', '減重'), ('maintain', '維持體重'), ('gain_muscle', '增肌')], default='maintain', help_text='目標', max_length=20, verbose_name='目標'),
        ),
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='身高 (cm)', max_digits=5, null=True, verbose_name='身高 (cm)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_ai_provider',
            field=models.CharField(choices=[('openai', 'OpenAI GPT'), ('gemini', 'Google Gemini')], default='openai', help_text='偏好的AI模型提供者', max_length=20, verbose_name='偏好的AI模型提供者'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='更新時間', verbose_name='更新時間'),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='體重 (kg)', max_digits=5, null=True, verbose_name='體重 (kg)'),
        ),
    ]
