# Generated by Django 5.0.6 on 2026-05-23 16:44

import users.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_daily_calorie_target_user_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gemini_api_key',
            field=users.fields.EncryptedCharField(blank=True, null=True, verbose_name='Gemini API Key'),
        ),
        migrations.AddField(
            model_name='user',
            name='openai_api_key',
            field=users.fields.EncryptedCharField(blank=True, null=True, verbose_name='OpenAI API Key'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_gemini_model',
            field=models.CharField(default='gemini-2.5-flash', max_length=100, verbose_name='偏好的 Gemini 模型'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_openai_model',
            field=models.CharField(default='gpt-4o-mini', max_length=100, verbose_name='偏好的 OpenAI 模型'),
        ),
    ]
