[pytest]
DJANGO_SETTINGS_MODULE = config.settings.testing # Django執行測試時要載入的設定檔
python_files = tests/*.py tests/**/*.py # 指定tests底下的檔案的測試檔案
python_classes = Test*  
python_functions = test_*
addopts = --reuse-db -v --tb=short  # 增加測試選項