# Generated by Django 5.0.6 on 2026-04-14 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nutrition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='紀錄日期')),
                ('meal_type', models.CharField(choices=[('breakfast', '早餐'), ('lunch', '午餐'), ('dinner', '晚餐'), ('snack', '點心')], help_text='餐別', max_length=20)),
                ('remark', models.TextField(blank=True, help_text='備註')),
                ('total_calories', models.DecimalField(decimal_places=2, default=0, help_text='總熱量 (kcal)', max_digits=8)),
                ('total_protein', models.DecimalField(decimal_places=2, default=0, help_text='總蛋白質 (g)', max_digits=8)),
                ('total_carbs', models.DecimalField(decimal_places=2, default=0, help_text='總碳水化合物 (g)', max_digits=8)),
                ('total_fat', models.DecimalField(decimal_places=2, default=0, help_text='總脂肪 (g)', max_digits=8)),
                ('total_fiber', models.DecimalField(decimal_places=2, default=0, help_text='總膳食纖維 (g)', max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新時間')),
                ('user', models.ForeignKey(help_text='使用者', on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '飲食日記',
                'db_table': 'diary_entries',
                'ordering': ['user', '-date', '-meal_type'],
            },
        ),
        migrations.CreateModel(
            name='DiaryFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_g', models.DecimalField(decimal_places=2, help_text='食用量 (g)', max_digits=7)),
                ('diary_entry', models.ForeignKey(help_text='所屬日記', on_delete=django.db.models.deletion.CASCADE, related_name='diary_foods', to='diary.diaryentry')),
                ('food', models.ForeignKey(help_text='食物', on_delete=django.db.models.deletion.CASCADE, to='nutrition.food')),
            ],
            options={
                'verbose_name': '日記食物明細',
                'db_table': 'diary_foods',
            },
        ),
    ]
