# Generated by Django 5.0.6 on 2026-04-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryfood',
            name='remark',
            field=models.TextField(blank=True, help_text='備註'),
        ),
    ]
