# Generated by Django 5.0.6 on 2026-04-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_diaryfood_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaryentry',
            name='total_calories',
        ),
        migrations.RemoveField(
            model_name='diaryentry',
            name='total_carbs',
        ),
        migrations.RemoveField(
            model_name='diaryentry',
            name='total_fat',
        ),
        migrations.RemoveField(
            model_name='diaryentry',
            name='total_fiber',
        ),
        migrations.RemoveField(
            model_name='diaryentry',
            name='total_protein',
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='calories',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='AI分析熱量 (kcal)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='carbohydrates',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='AI分析碳水化合物 (g)', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='fat',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='AI分析脂肪 (g)', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='food_name',
            field=models.CharField(default='unknown', help_text='食物名稱，例如:雞腿便當、綠茶', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='image',
            field=models.ImageField(blank=True, help_text='食物照片(AI辨識使用)', null=True, upload_to='diary_images/%Y/%m'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='portion_description',
            field=models.CharField(blank=True, help_text='分量描述，例如:一碗、半碗、一杯', max_length=200),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='protein',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='AI分析蛋白質 (g)', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='saturated_fat',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='AI分析飽和脂肪 (g)', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='sodium',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='AI分析納 (g)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='status',
            field=models.CharField(choices=[('pending', '等待分析'), ('completed', '分析完成'), ('failed', '分析失敗')], default='pending', help_text='AI分析狀態', max_length=20),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='sugar',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='AI分析糖 (g)', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='trans_fat',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='AI分析反式脂肪 (g)', max_digits=7, null=True),
        ),
        migrations.DeleteModel(
            name='DiaryFood',
        ),
    ]
