# Generated by Django 5.0.6 on 2026-05-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_remove_diaryentry_total_calories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='status',
            field=models.CharField(choices=[('pending', '等待分析'), ('processing', '分析中'), ('completed', '分析完成'), ('failed', '分析失敗')], default='pending', help_text='AI分析狀態', max_length=20),
        ),
    ]
