# Generated by Django 5.0.6 on 2026-05-18 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_alter_diaryentry_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(help_text='成分名稱，例如:雞肉絲、白飯', max_length=200, verbose_name='食物名稱')),
                ('portion_description', models.CharField(blank=True, help_text='預估份量', max_length=200, verbose_name='預估份量')),
                ('calories', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='卡路里')),
                ('protein', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='蛋白質')),
                ('fat', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='脂肪')),
                ('saturated_fat', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='飽和脂肪')),
                ('trans_fat', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='反式脂肪')),
                ('carbohydrates', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='碳水化合物')),
                ('sugar', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='糖')),
                ('sodium', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='納')),
                ('source', models.CharField(choices=[('ai_vision', 'AI視覺辨識'), ('ai_text', 'AI文字分析'), ('cache', '快取')], max_length=20)),
                ('diary_entry', models.ForeignKey(help_text='所屬日記', on_delete=django.db.models.deletion.CASCADE, related_name='components', to='diary.diaryentry', verbose_name='日記所屬')),
            ],
            options={
                'verbose_name': '食物成份明細',
                'db_table': 'diary_components',
            },
        ),
    ]
