# Generated by Django 5.0.6 on 2026-05-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_diarycomponent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diarycomponent',
            options={'verbose_name': '食物成份明細', 'verbose_name_plural': '食物成份明細'},
        ),
        migrations.AlterField(
            model_name='diarycomponent',
            name='source',
            field=models.CharField(choices=[('ai_vision', 'AI視覺辨識'), ('ai_text', 'AI文字分析'), ('cache', '快取')], default='ai_vision', max_length=20),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='status',
            field=models.CharField(choices=[('pending', '等待分析'), ('nutrition_resolving', '解析營養成分中'), ('nutrition_resolved', '營養成分已就緒'), ('ai_analyzing', '產生建議中'), ('completed', '分析完成'), ('failed', '分析失敗'), ('processing', '分析中')], default='pending', help_text='AI分析狀態', max_length=20),
        ),
    ]
