# Generated by Django 5.0.6 — DiaryEntry 預設排序加上 -id tie-breaker

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_alter_diaryentry_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diaryentry',
            options={'ordering': ['user', '-date', '-meal_type', '-id'], 'verbose_name': '飲食日記'},
        ),
    ]
