# Generated by Django 5.0.6 on 2026-05-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_alter_diaryentry_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarycomponent',
            name='sodium',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='鈉'),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='sodium',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='AI分析鈉 (mg)', max_digits=8, null=True),
        ),
    ]
