# Generated by Django 5.0.6 on 2026-04-14 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_sent', models.TextField(help_text='發送給AI的提示詞')),
                ('raw_response', models.TextField(help_text='AI原始回應')),
                ('summary', models.TextField(help_text='AI 分析結果')),
                ('suggestions', models.JSONField(default=list, help_text='AI 分析建議')),
                ('nutrition_score', models.IntegerField(blank=True, help_text='營養評分 1-100', null=True)),
                ('status', models.CharField(choices=[('pending', '待分析'), ('processing', '分析中'), ('completed', '完成'), ('failed', '失敗')], default='pending', help_text='狀態', max_length=20)),
                ('ai_model_used', models.CharField(help_text='使用的 AI 模型(gpt-4o / gemini-pro)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diary_entry', models.OneToOneField(help_text='一筆紀錄只對應一份 AI 分析結果', on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='diary.diaryentry')),
                ('user', models.ForeignKey(help_text='使用者', on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI 分析結果',
                'db_table': 'ai_analyses',
            },
        ),
    ]
