# Generated by Django 5.0.6 on 2026-04-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='exceeded_nutrients',
            field=models.JSONField(default=list, help_text='攝取過多的營養素'),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='lacking_nutrients',
            field=models.JSONField(default=list, help_text='攝取不足的營養素'),
        ),
        migrations.AlterField(
            model_name='aianalysis',
            name='ai_model_used',
            field=models.CharField(help_text='使用的 AI 模型', max_length=50),
        ),
    ]
