# Generated by Django 5.0.6 on 2026-05-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0002_aianalysis_exceeded_nutrients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aianalysis',
            name='status',
            field=models.CharField(choices=[('pending', '等待分析'), ('nutrition_resolving', '解析營養成分中'), ('nutrition_resolved', '營養成分已就緒'), ('ai_analyzing', '產生建議中'), ('completed', '分析完成'), ('failed', '分析失敗'), ('processing', '分析中')], default='pending', help_text='狀態', max_length=20),
        ),
    ]
