# Generated by Django 5.0.6 on 2026-05-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0003_alter_aianalysis_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aianalysis',
            name='status',
            field=models.CharField(choices=[('pending', '等待分析'), ('processing', '分析中'), ('completed', '分析完成'), ('failed', '分析失敗')], default='completed', help_text='狀態', max_length=20),
        ),
    ]
