# Generated by Django 5.0.6 on 2026-04-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='食物名稱', max_length=100)),
                ('category', models.CharField(choices=[('grain', '主食/穀類'), ('protein', '蛋白質'), ('vegetable', '蔬菜'), ('fruit', '水果'), ('dairy', '乳製品'), ('fat', '油脂'), ('beverage', '飲料'), ('other', '其他')], default='other', help_text='食物類別', max_length=20)),
                ('calories_per_100g', models.DecimalField(decimal_places=2, help_text='熱量 (g / 100g)', max_digits=7)),
                ('protein_per_100g', models.DecimalField(decimal_places=2, help_text='蛋白質 (g / 100g)', max_digits=6)),
                ('carbs_per_100g', models.DecimalField(decimal_places=2, help_text='碳水化合物 (g / 100g)', max_digits=6)),
                ('fat_per_100g', models.DecimalField(decimal_places=2, help_text='脂肪 (g / 100g)', max_digits=6)),
                ('fiber_per_100g', models.DecimalField(decimal_places=2, default=0, help_text='膳食纖維 (g / 100g)', max_digits=6)),
                ('food_image', models.ImageField(blank=True, help_text='食物圖片 (AI 圖片辨識用)', null=True, upload_to='foods/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新時間')),
            ],
            options={
                'verbose_name': '食物資料庫',
                'db_table': 'foods',
                'ordering': ['name'],
            },
        ),
    ]
