# Generated by Django 5.0.6 on 2026-04-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodNutritionCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(help_text='食物名稱，作為查詢的key', max_length=200, unique=True)),
                ('calories', models.DecimalField(decimal_places=2, help_text='熱量 (kcal)', max_digits=8)),
                ('protein', models.DecimalField(decimal_places=2, help_text='蛋白質 (g)', max_digits=7)),
                ('fat', models.DecimalField(decimal_places=2, help_text='脂肪 (g)', max_digits=7)),
                ('saturated_fat', models.DecimalField(decimal_places=2, help_text='飽和脂肪 (g)', max_digits=7)),
                ('trans_fat', models.DecimalField(decimal_places=2, help_text='反式脂肪 (g)', max_digits=7)),
                ('carbohydrates', models.DecimalField(decimal_places=2, help_text='碳水化合物 (g)', max_digits=7)),
                ('sugar', models.DecimalField(decimal_places=2, help_text='糖 (g)', max_digits=7)),
                ('sodium', models.DecimalField(decimal_places=2, help_text='鈉 (mg)', max_digits=7)),
                ('food_description', models.TextField(blank=True, help_text='食物描述，AI分析的原始文字描述')),
                ('ai_model_used', models.CharField(blank=True, help_text='使用的AI模型名稱', max_length=100)),
                ('hit_count', models.IntegerField(default=0, help_text='被查詢的次數，作為熱門程度的指標')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新時間')),
            ],
            options={
                'verbose_name': '食物營養快取資料庫',
                'db_table': 'food_nutrition_cache',
            },
        ),
    ]
