# Generated by Django 5.0.6 on 2026-05-23 16:44

import pgvector.django.vector
from django.db import migrations, models


def create_vector_extension(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute("CREATE EXTENSION IF NOT EXISTS vector")


def drop_vector_extension(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute("DROP EXTENSION IF EXISTS vector")


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_foodnutritioncache'),
    ]

    operations = [
        migrations.RunPython(create_vector_extension, drop_vector_extension),
        migrations.AddField(
            model_name='foodnutritioncache',
            name='data_source',
            field=models.CharField(choices=[('ai', 'AI分析'), ('taiwan_fda', '衛福部FDA'), ('manual', '手動')], default='ai', help_text='營養資料的來源', max_length=20),
        ),
        migrations.AddField(
            model_name='foodnutritioncache',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
