# Generated by Django 5.0.6 on 2026-05-25 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_foodnutritioncache_data_source_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['name', 'id'], 'verbose_name': '食物資料庫'},
        ),
    ]
